# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_data(object):
    def setupUi(self, Form_data):
        Form_data.setObjectName("Form_data")
        Form_data.resize(1085, 636)
        Form_data.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form_data)
        self.gridLayout.setContentsMargins(0, 0, 0, 1)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_datainfo = QtWidgets.QTableWidget(Form_data)
        self.tableWidget_datainfo.setMaximumSize(QtCore.QSize(16777215, 61))
        self.tableWidget_datainfo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_datainfo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_datainfo.setAutoFillBackground(True)
        self.tableWidget_datainfo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_datainfo.setLineWidth(1)
        self.tableWidget_datainfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_datainfo.setShowGrid(False)
        self.tableWidget_datainfo.setRowCount(1)
        self.tableWidget_datainfo.setColumnCount(6)
        self.tableWidget_datainfo.setObjectName("tableWidget_datainfo")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_datainfo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_datainfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_datainfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_datainfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_datainfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_datainfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_datainfo.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.tableWidget_datainfo, 0, 0, 1, 1)
        self.widget_func = QtWidgets.QWidget(Form_data)
        self.widget_func.setObjectName("widget_func")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_func)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_daorusj = QtWidgets.QPushButton(self.widget_func)
        self.pushButton_daorusj.setObjectName("pushButton_daorusj")
        self.horizontalLayout.addWidget(self.pushButton_daorusj)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.widget_func)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateTimeEdit_datastart = QtWidgets.QDateTimeEdit(self.widget_func)
        self.dateTimeEdit_datastart.setCalendarPopup(True)
        self.dateTimeEdit_datastart.setObjectName("dateTimeEdit_datastart")
        self.horizontalLayout.addWidget(self.dateTimeEdit_datastart)
        self.label_2 = QtWidgets.QLabel(self.widget_func)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dateTimeEdit_dataend = QtWidgets.QDateTimeEdit(self.widget_func)
        self.dateTimeEdit_dataend.setCalendarPopup(True)
        self.dateTimeEdit_dataend.setObjectName("dateTimeEdit_dataend")
        self.horizontalLayout.addWidget(self.dateTimeEdit_dataend)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_plotfig = QtWidgets.QPushButton(self.widget_func)
        self.pushButton_plotfig.setObjectName("pushButton_plotfig")
        self.horizontalLayout.addWidget(self.pushButton_plotfig)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_txt = QtWidgets.QPushButton(self.widget_func)
        self.pushButton_txt.setObjectName("pushButton_txt")
        self.horizontalLayout.addWidget(self.pushButton_txt)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget_func, 1, 0, 1, 2)
        self.widget = QtWidgets.QWidget(Form_data)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_fig = QtWidgets.QGridLayout()
        self.gridLayout_fig.setObjectName("gridLayout_fig")
        self.gridLayout_3.addLayout(self.gridLayout_fig, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 16)

        self.retranslateUi(Form_data)
        QtCore.QMetaObject.connectSlotsByName(Form_data)

    def retranslateUi(self, Form_data):
        _translate = QtCore.QCoreApplication.translate
        Form_data.setWindowTitle(_translate("Form_data", "Form"))
        self.tableWidget_datainfo.setSortingEnabled(False)
        item = self.tableWidget_datainfo.horizontalHeaderItem(0)
        item.setText(_translate("Form_data", "数据名称"))
        item = self.tableWidget_datainfo.horizontalHeaderItem(1)
        item.setText(_translate("Form_data", "剖面个数"))
        item = self.tableWidget_datainfo.horizontalHeaderItem(2)
        item.setText(_translate("Form_data", "开始时间"))
        item = self.tableWidget_datainfo.horizontalHeaderItem(3)
        item.setText(_translate("Form_data", "结束时间"))
        item = self.tableWidget_datainfo.horizontalHeaderItem(4)
        item.setText(_translate("Form_data", "最小深度"))
        item = self.tableWidget_datainfo.horizontalHeaderItem(5)
        item.setText(_translate("Form_data", "最大深度"))
        self.pushButton_daorusj.setText(_translate("Form_data", "导入数据"))
        self.label.setText(_translate("Form_data", "时间段："))
        self.dateTimeEdit_datastart.setDisplayFormat(_translate("Form_data", "yyyy/MM/dd HH:mm:ss.zzz"))
        self.label_2.setText(_translate("Form_data", "至"))
        self.dateTimeEdit_dataend.setDisplayFormat(_translate("Form_data", "yyyy/MM/dd HH:mm:ss.zzz"))
        self.pushButton_plotfig.setText(_translate("Form_data", "生成运动图像"))
        self.pushButton_txt.setText(_translate("Form_data", "生成运动状态拐点文件"))
