# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1345, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_header = QtWidgets.QWidget(self.centralwidget)
        self.widget_header.setMaximumSize(QtCore.QSize(16777215, 81))
        self.widget_header.setObjectName("widget_header")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_header)
        self.gridLayout_2.setContentsMargins(2, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_icon = QtWidgets.QPushButton(self.widget_header)
        self.pushButton_icon.setMaximumSize(QtCore.QSize(101, 81))
        self.pushButton_icon.setText("")
        self.pushButton_icon.setObjectName("pushButton_icon")
        self.gridLayout_2.addWidget(self.pushButton_icon, 0, 0, 2, 1)
        self.pushButton_fanda = QtWidgets.QPushButton(self.widget_header)
        self.pushButton_fanda.setMaximumSize(QtCore.QSize(42, 26))
        self.pushButton_fanda.setText("")
        self.pushButton_fanda.setObjectName("pushButton_fanda")
        self.gridLayout_2.addWidget(self.pushButton_fanda, 0, 3, 1, 1)
        self.pushButton_guanbi = QtWidgets.QPushButton(self.widget_header)
        self.pushButton_guanbi.setMaximumSize(QtCore.QSize(42, 26))
        self.pushButton_guanbi.setText("")
        self.pushButton_guanbi.setObjectName("pushButton_guanbi")
        self.gridLayout_2.addWidget(self.pushButton_guanbi, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 3, 1, 1)
        self.pushButton_zuixiao = QtWidgets.QPushButton(self.widget_header)
        self.pushButton_zuixiao.setMaximumSize(QtCore.QSize(42, 26))
        self.pushButton_zuixiao.setText("")
        self.pushButton_zuixiao.setObjectName("pushButton_zuixiao")
        self.gridLayout_2.addWidget(self.pushButton_zuixiao, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_header)
        self.label.setStyleSheet("font: 22pt \"华光超粗黑_CNKI\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 2, 1)
        self.gridLayout.addWidget(self.widget_header, 0, 0, 1, 2)
        self.widget_Menu = QtWidgets.QWidget(self.centralwidget)
        self.widget_Menu.setMaximumSize(QtCore.QSize(191, 16777215))
        self.widget_Menu.setAutoFillBackground(False)
        self.widget_Menu.setObjectName("widget_Menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_Menu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_1home = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_1home.setMinimumSize(QtCore.QSize(191, 23))
        self.pushButton_1home.setAutoFillBackground(False)
        self.pushButton_1home.setObjectName("pushButton_1home")
        self.verticalLayout.addWidget(self.pushButton_1home)
        self.pushButton_2data = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_2data.setObjectName("pushButton_2data")
        self.verticalLayout.addWidget(self.pushButton_2data)
        self.pushButton_3Fig = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_3Fig.setObjectName("pushButton_3Fig")
        self.verticalLayout.addWidget(self.pushButton_3Fig)
        self.pushButton_4yaosu = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_4yaosu.setObjectName("pushButton_4yaosu")
        self.verticalLayout.addWidget(self.pushButton_4yaosu)
        self.pushButton_5TDFig = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_5TDFig.setObjectName("pushButton_5TDFig")
        self.verticalLayout.addWidget(self.pushButton_5TDFig)
        self.pushButton_6SDFig = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_6SDFig.setObjectName("pushButton_6SDFig")
        self.verticalLayout.addWidget(self.pushButton_6SDFig)
        self.pushButton_7TProFig = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_7TProFig.setObjectName("pushButton_7TProFig")
        self.verticalLayout.addWidget(self.pushButton_7TProFig)
        self.pushButton_8SProFig = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_8SProFig.setObjectName("pushButton_8SProFig")
        self.verticalLayout.addWidget(self.pushButton_8SProFig)
        self.pushButton_help = QtWidgets.QPushButton(self.widget_Menu)
        self.pushButton_help.setObjectName("pushButton_help")
        self.verticalLayout.addWidget(self.pushButton_help)
        self.gridLayout.addWidget(self.widget_Menu, 1, 0, 2, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout.addWidget(self.frame_3, 1, 1, 2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1345, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "浮标数据分析系统"))
        self.pushButton_1home.setText(_translate("MainWindow", "  首页"))
        self.pushButton_2data.setText(_translate("MainWindow", "  浮标数据"))
        self.pushButton_3Fig.setText(_translate("MainWindow", "  数据曲线"))
        self.pushButton_4yaosu.setText(_translate("MainWindow", "要素-深度 分布图"))
        self.pushButton_5TDFig.setText(_translate("MainWindow", "温度-深度 折线图"))
        self.pushButton_6SDFig.setText(_translate("MainWindow", "盐度-深度 折线图"))
        self.pushButton_7TProFig.setText(_translate("MainWindow", "  温度剖面图"))
        self.pushButton_8SProFig.setText(_translate("MainWindow", "  盐度剖面图"))
        self.pushButton_help.setText(_translate("MainWindow", "  使用帮助"))
